component_depth: 1

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - fake/entry

  - name: go
    test:
      include:
        - *.mdr
      exclude:
        - *.md
