component_depth: 1

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c

  - name: go
    production:
      include:
       - fake_entry
    test:
      include:
        - .*\.mdr
        - /tests/.*/.*\.mdr
