language: haskell

os:
  - linux
  - osx

matrix:
   - os: osx
             
#install:
#  - cabal install alex happy

#script: LEX="cabal run alex" YACC="cabal run happy" make && make test

allow_failures:
  - os: osx
