language: haskell

os:
  - linux
  - osx
#  - windows

env:
  - LEX="cabal run alex"
  - YACC="cabal run happy"
matrix:
  allow_failures:
    - compiler: clang
#   - os: osx
#  - os: windows
             
compiler:
  - gcc
  - clang

install:
  - cabal install alex happy

script: make && make test

#allow_failures:

#install:
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then gem install coveralls-lcov; fi
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then export USE_COVERAGE=1; fi

#after_success:
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then lcov --no-external --capture --directory src --output-file mdr.info; fi
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then ls; fi
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then coveralls-lcov mdr.info; fi
