language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

script: make && make test

allow_failures:
  - os: windows

install:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then gem install coveralls-lcov; fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then export USE_COVERAGE=1; fi

after_success:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then lcov --no-external --capture --directory src --output-file mdr.info fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then genhtml -q -s -t "Mdr: coverage" -o lcov --precision 2 $OUTFILE
